[tool.poetry]
name = "CookieBlock-consent-crawler"
version = "0.1-dev"
description = "Classification service for privacy policies and terms and conditions"
authors = ["Karel Kubicek", "Dino Bollinger"]
readme = "README.md"
package-mode = false

[tool.poetry.scripts]
presence_crawl = "service:main"
consent_crawl = "service:main"

# ATTENTION: python 3.11.9 is needed as 3.12 is not supported by js2py as of 14.06.2024
# Due to: https://github.com/tsukumijima/tweepy-authlib/issues/5
[tool.poetry.dependencies]
python = "3.11.9"
docopt = "^0.6.2"
tqdm = "^4.66.4"
tblib = "^3.0.0"
scikit-learn = "^1.5.0"
requests = "^2.32.2"
pebble = "^5.0.7"
psutil = "^5.9.8"
multiprocess = "^0.70.16"
selenium = "^4.21.0"
pillow = "^10.3.0"
domain-utils = "^0.7.1"
bs4 = "^0.0.2"
js2py = "0.70"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
