
###############################################################################
# This file is the docker-compose used for crawls.
# Adapt the -n argument in the service 'crawler' command for more or less
# parallelism.
###############################################################################

services:
  regular1:
    restart: "no"
    image: infsec-server.inf.ethz.ch/cb-cc/crawler:0.25
    command: >
      sh -c "\
              presence_crawl --numthreads 256 -f list.txt --batches 100 && \
              cat ./filtered_domains/cookiebot_responses.txt ./filtered_domains/onetrust_responses.txt > ./consent_crawl_list.txt && \
              consent_crawl -n 12 --profile_tar profile_consentomatic_accept_all.tar.gz --file ./consent_crawl_list.txt"
    stop_grace_period: 1m           # Leaves some time to stop the crawler
    stop_signal: SIGINT             # Same as Ctrl+C
    volumes:
      - ./list.txt:/crawler/list.txt
      - ./collected_data/:/crawler/collected_data
      - ./filtered_domains/:/crawler/filtered_domains
    shm_size: 4gb                   # Needed by chrome/chromedriver
    hostname: cb-cc-crawler

networks:
  cb-cc-open:
    name: cb-cc-open
    internal: false
    ipam:
      driver: default
